// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"authority-api/internal/biz"
	"authority-api/internal/conf"
	"authority-api/internal/data"
	"authority-api/internal/server"
	"authority-api/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/go-kratos/kratos/v2/registry"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(logger log.Logger, registrar registry.Registrar, bootstrap *conf.Bootstrap) (*kratos.App, func(), error) {
	client := data.NewRedisClient(bootstrap, logger)
	discovery := data.NewDiscovery(bootstrap)
	authorityClient := data.NewMenuServiceClient(discovery, bootstrap)
	dataData, cleanup, err := data.NewData(client, authorityClient, logger)
	if err != nil {
		return nil, nil, err
	}
	menuRepo := data.NewMenuRepo(dataData, logger)
	menuUseCase := biz.NewMenuUseCase(menuRepo, logger)
	menuService := service.NewMenuService(menuUseCase, logger)
	httpServer := server.NewHTTPServer(bootstrap, menuService, logger)
	app := newApp(logger, httpServer, registrar)
	return app, func() {
		cleanup()
	}, nil
}
