name: user-rpc-rpc-api.api
server:
  http:
    addr: 0.0.0.0:8901
    timeout: 2s
  kafka:
    addrs:
      - localhost:9092
  rocketmq:
    addrs:
      - 101.42.237.244:9876
data:
  redis:
    addr: 101.42.237.244:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
trace:
  endpoint: http://101.42.237.244:14268/api/traces
auth:
  jwt_key: hqFr%3ddt32DGlSTOI5cO6@TH#fFwYnP$S
service:
  user:
    endpoint: discovery:///kratos-shop.user-rpc-rpc-api.service