server:
  http:
    addr: 0.0.0.0:5020
    timeout: 1s
  grpc:
    addr: 0.0.0.0:6020
    timeout: 1s
data:
  database:
    driver: mysql
    source: root:root@tcp(127.0.0.1:3306)/authority?charset=utf8mb4&parseTime=True&loc=Local
  redis:
    addr: 101.42.237.244:6379
    dial_timeout: 2s
    read_timeout: 2s
    write_timeout: 2s
tracer:
  endpoint: http://101.42.237.244:14268/api/traces
  batcher: "jaeger"
  sampler: 1.0
  env: "dev"
