// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/go-kratos/kratos/v2/registry"
	"user-job/internal/biz"
	"user-job/internal/conf"
	"user-job/internal/data"
	"user-job/internal/server"
	"user-job/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(logger log.Logger, registrar registry.Registrar, bootstrap *conf.Bootstrap) (*kratos.App, func(), error) {
	discovery := data.NewDiscovery(bootstrap)
	userClient := data.NewUserServiceClient(discovery, bootstrap)
	dataData, cleanup, err := data.NewData(userClient, logger)
	if err != nil {
		return nil, nil, err
	}
	userRepo := data.NewUserRepo(dataData, logger)
	userUseCase := biz.NewUserUseCase(userRepo, logger, userClient)
	userService := service.NewUserService(userUseCase, logger)
	rocketmqServer := server.NewRocketmqServer(bootstrap, userService, logger)
	asynqServer := server.NewAsynqServer(bootstrap, logger)
	app := newApp(logger, registrar, rocketmqServer, asynqServer)
	return app, func() {
		cleanup()
	}, nil
}
